apiVersion: v1
kind: Secret
metadata:
  name: harbor-registry
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJoYXJib3IucGV6bC5sb2NhbCI6IHsKICAgICAgImF1dGgiOiAiWVdSdGFXNDZTR0Z5WW05eU1USXpORFU9IgogICAgfQogIH0KfQ==
type: kubernetes.io/dockerconfigjson
